### PR TITLE
Add Stringer 3.0.9 StringerEncription and Smoke Number Obfuscation support

### PR DESCRIPTION
**Pull request by FFY00**
The code was from c001man's repository. He deleted it but I still had a local clone with the commits so I forked your repo and added the changes.

### CODE REVIEW

**Comment by FireMasterK** [comment]
Thanks

**Comment by XawierStudio** [comment]
@FFY00 can you reupload .jar and .bat to https://ci.samczsun.com/job/Deobfuscator/ ? i cant compile bcs dont ahve libs ;;_;

**Comment by ItzSomebody** [comment]
He can't because that is samczun's CI build server

**Comment by XawierStudio** [comment]
@ItzSomebody or can you gimme me? if you have? :v:

**Comment by ItzSomebody** [comment]
I have the one by Coolman before he deleted his repository, is that the one?

**Comment by XawierStudio** [comment]
hmm i think so

**Comment by FFY00** [comment]
I have the jar in my build server. There's no need for any .bat files, you have the maven configuration, just use maven to build it. Sorry for the late response, my house is getting paint, so I'm living somewhere else and my desktop is packed up in a box.

**Pull request merged**
